package net.caiban.domain.eshop;

import java.util.Date;

/**
 * EshopAccount generated by MyEclipse Persistence Tools
 */

public class EshopAccount implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer eid;
	private Integer uid;
	private String account;
	private String name;
	private Short blocked;
	private Date gmtcreate;

	// Constructors

	/** default constructor */
	public EshopAccount() {
	}

	/** minimal constructor */
	public EshopAccount(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public EshopAccount(Integer id, Integer eid, Integer uid, String account,
			String name, Short blocked, Date gmtcreate) {
		this.id = id;
		this.eid = eid;
		this.uid = uid;
		this.account = account;
		this.name = name;
		this.blocked = blocked;
		this.gmtcreate = gmtcreate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getBlocked() {
		return this.blocked;
	}

	public void setBlocked(Short blocked) {
		this.blocked = blocked;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

}