package net.caiban.domain.eshop;

import java.util.Date;

/**
 * EshopBuyer generated by MyEclipse Persistence Tools
 */

public class EshopBuyer implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String phone;
	private String email;
	private String im;
	private Short valuable;
	private Integer uid;
	private Integer eid;
	private Date gmtcreate;
	private String remark;

	// Constructors

	/** default constructor */
	public EshopBuyer() {
	}

	/** minimal constructor */
	public EshopBuyer(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public EshopBuyer(Integer id, String name, String phone, String email,
			String im, Short valuable, Integer uid, Integer eid, Date gmtcreate, String remark) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.im = im;
		this.valuable = valuable;
		this.uid = uid;
		this.eid = eid;
		this.gmtcreate = gmtcreate;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getIm() {
		return this.im;
	}

	public void setIm(String im) {
		this.im = im;
	}

	public Short getValuable() {
		return this.valuable;
	}

	public void setValuable(Short valuable) {
		this.valuable = valuable;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

	/**
	 * @return the remark
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * @param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

}