package net.caiban.domain.orders;

import java.util.Date;

/**
 * Logistics generated by MyEclipse Persistence Tools
 */

public class Logistics implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String phone;
	private String address;
	private String routes;
	private String arrivalArea;
	private String remark;
	private Integer uid;
	private Integer eid;
	private Date gmtcreate;

	// Constructors

	/** default constructor */
	public Logistics() {
	}

	/** minimal constructor */
	public Logistics(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Logistics(Integer id, String name, String phone, String address,
			String routes, String arrivalArea, String remark, Integer uid,
			Integer eid, Date gmtcreate) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.routes = routes;
		this.arrivalArea = arrivalArea;
		this.remark = remark;
		this.uid = uid;
		this.eid = eid;
		this.gmtcreate = gmtcreate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRoutes() {
		return this.routes;
	}

	public void setRoutes(String routes) {
		this.routes = routes;
	}

	public String getArrivalArea() {
		return this.arrivalArea;
	}

	public void setArrivalArea(String arrivalArea) {
		this.arrivalArea = arrivalArea;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

}