package net.caiban.domain.orders;

/**
 * OrderProduct generated by MyEclipse Persistence Tools
 */

public class OrdersProduct implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer productId;
	private Integer ordersId;
	private String priceDiscount;
	private Integer quantity;

	// Constructors

	/** default constructor */
	public OrdersProduct() {
	}

	/** minimal constructor */
	public OrdersProduct(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public OrdersProduct(Integer id, Integer productId, Integer ordersId,
			String priceDiscount, Integer quantity) {
		this.id = id;
		this.productId = productId;
		this.ordersId = ordersId;
		this.priceDiscount = priceDiscount;
		this.quantity = quantity;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPriceDiscount() {
		return this.priceDiscount;
	}

	public void setPriceDiscount(String priceDiscount) {
		this.priceDiscount = priceDiscount;
	}

	/**
	 * @return the productId
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * @param productId the productId to set
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * @return the ordersId
	 */
	public Integer getOrdersId() {
		return ordersId;
	}

	/**
	 * @param ordersId the ordersId to set
	 */
	public void setOrdersId(Integer ordersId) {
		this.ordersId = ordersId;
	}

	/**
	 * @return the quantity
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * @param quantity the quantity to set
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}