package net.caiban.domain.orders;

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;

/**
 * Orders generated by MyEclipse Persistence Tools
 */

public class Orders implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String orderNo;
	private String orderNoTaobao;
	private Integer buyerId;
	private String payment;
	private Float totalOrderCash;
	private Float totalProductCash;
	private Float paid;
	private Date gmtOrder;
	private Short orderStatus;
	private Integer uid;
	private Integer eid;
	private Date gmtcreate;

	// Constructors

	/** default constructor */
	public Orders() {
	}

	/** minimal constructor */
	public Orders(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Orders(Integer id, String orderNo, String orderNoTaobao,
			Integer buyerId, String payment, Float totalOrderCash,
			Float totalProductCash, Float paid, Date gmtOrder,
			Short orderStatus, Integer uid, Integer eid, Date gmtcreate) {
		this.id = id;
		this.orderNo = orderNo;
		this.orderNoTaobao = orderNoTaobao;
		this.buyerId = buyerId;
		this.payment = payment;
		this.totalOrderCash = totalOrderCash;
		this.totalProductCash = totalProductCash;
		this.paid = paid;
		this.gmtOrder = gmtOrder;
		this.orderStatus = orderStatus;
		this.uid = uid;
		this.eid = eid;
		this.gmtcreate = gmtcreate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getOrderNoTaobao() {
		return this.orderNoTaobao;
	}

	public void setOrderNoTaobao(String orderNoTaobao) {
		this.orderNoTaobao = orderNoTaobao;
	}

	public Integer getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(Integer buyerId) {
		this.buyerId = buyerId;
	}

	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	public Float getTotalOrderCash() {
		return this.totalOrderCash;
	}

	public void setTotalOrderCash(Float totalOrderCash) {
		this.totalOrderCash = totalOrderCash;
	}

	public Float getTotalProductCash() {
		return this.totalProductCash;
	}

	public void setTotalProductCash(Float totalProductCash) {
		this.totalProductCash = totalProductCash;
	}

	public Float getPaid() {
		return this.paid;
	}

	public void setPaid(Float paid) {
		this.paid = paid;
	}

	@JSON(format="yyyy-MM-dd")
	public Date getGmtOrder() {
		return this.gmtOrder;
	}

	public void setGmtOrder(Date gmtOrder) {
		this.gmtOrder = gmtOrder;
	}

	public Short getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Short orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

}