package net.caiban.domain.orders;

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;

/**
 * SaleDispute generated by MyEclipse Persistence Tools
 */

public class SaleDispute implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer orderId;
	private Short returnGoods;
	private Float reparation;
	private String remark;
	private Date period;
	private Short severity;
	private Short resolved;
	private Integer resolvedUid;
	private Integer uid;
	private Integer eid;
	private Date gmtcreate;

	// Constructors

	/** default constructor */
	public SaleDispute() {
	}

	/** minimal constructor */
	public SaleDispute(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public SaleDispute(Integer id, Integer orderId, Short returnGoods,
			Float reparation, String remark, Date period, Short severity,
			Short resolved, Integer resolvedUid, Integer uid, Integer eid,
			Date gmtcreate) {
		this.id = id;
		this.orderId = orderId;
		this.returnGoods = returnGoods;
		this.reparation = reparation;
		this.remark = remark;
		this.period = period;
		this.severity = severity;
		this.resolved = resolved;
		this.resolvedUid = resolvedUid;
		this.uid = uid;
		this.eid = eid;
		this.gmtcreate = gmtcreate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Short getReturnGoods() {
		return this.returnGoods;
	}

	public void setReturnGoods(Short returnGoods) {
		this.returnGoods = returnGoods;
	}

	public Float getReparation() {
		return this.reparation;
	}

	public void setReparation(Float reparation) {
		this.reparation = reparation;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@JSON(format="yyyy-MM-dd")
	public Date getPeriod() {
		return this.period;
	}

	public void setPeriod(Date period) {
		this.period = period;
	}

	public Short getSeverity() {
		return this.severity;
	}

	public void setSeverity(Short severity) {
		this.severity = severity;
	}

	public Short getResolved() {
		return this.resolved;
	}

	public void setResolved(Short resolved) {
		this.resolved = resolved;
	}

	public Integer getResolvedUid() {
		return this.resolvedUid;
	}

	public void setResolvedUid(Integer resolvedUid) {
		this.resolvedUid = resolvedUid;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

}