package net.caiban.domain.product;

import java.util.Date;

/**
 * ProductStock generated by MyEclipse Persistence Tools
 */

public class ProductStock implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer productId;
	private String barcode;
	private String batch;
	private Float amount;
	private Date gmtCheckin;
	private Date gmtCheckout;
	private Float amountCheckout;
	private String remark;
	private Date gmtcreate;
	private Integer uid;
	private Integer eid;
	
	private Integer logisticsDetailsId;

	// Constructors

	/** default constructor */
	public ProductStock() {
	}

	/** minimal constructor */
	public ProductStock(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ProductStock(Integer id, Integer productId, String barcode,
			String batch, Float amount, Date gmtCheckin, Date gmtCheckout,
			Float amountCheckout, String remark, Date gmtcreate, Integer uid,
			Integer eid) {
		this.id = id;
		this.productId = productId;
		this.barcode = barcode;
		this.batch = batch;
		this.amount = amount;
		this.gmtCheckin = gmtCheckin;
		this.gmtCheckout = gmtCheckout;
		this.amountCheckout = amountCheckout;
		this.remark = remark;
		this.gmtcreate = gmtcreate;
		this.uid = uid;
		this.eid = eid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Date getGmtCheckin() {
		return this.gmtCheckin;
	}

	public void setGmtCheckin(Date gmtCheckin) {
		this.gmtCheckin = gmtCheckin;
	}

	public Date getGmtCheckout() {
		return this.gmtCheckout;
	}

	public void setGmtCheckout(Date gmtCheckout) {
		this.gmtCheckout = gmtCheckout;
	}

	public Float getAmountCheckout() {
		return this.amountCheckout;
	}

	public void setAmountCheckout(Float amountCheckout) {
		this.amountCheckout = amountCheckout;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	/**
	 * @return the logisticsDetailsId
	 */
	public Integer getLogisticsDetailsId() {
		return logisticsDetailsId;
	}

	/**
	 * @param logisticsDetailsId the logisticsDetailsId to set
	 */
	public void setLogisticsDetailsId(Integer logisticsDetailsId) {
		this.logisticsDetailsId = logisticsDetailsId;
	}

	
}