package net.caiban.domain.product;

import java.util.Date;

/**
 * Product generated by MyEclipse Persistence Tools
 */

public class Product implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer productCategoryId;
	private String name;
	private String remark;
	private String model;
	private Float pricePurchase;
	private Float priceSale;
	private String unit;
	private String size;
	private Date gmtcreate;
	private Integer uid;
	private Integer eid;

	// Constructors

	/** default constructor */
	public Product() {
	}

	/** minimal constructor */
	public Product(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Product(Integer id, Integer productCategoryId, String name,
			String remark, String model, Float pricePurchase, Float priceSale,
			String unit, String size, Date gmtcreate, Integer uid, Integer eid) {
		this.id = id;
		this.productCategoryId = productCategoryId;
		this.name = name;
		this.remark = remark;
		this.model = model;
		this.pricePurchase = pricePurchase;
		this.priceSale = priceSale;
		this.unit = unit;
		this.size = size;
		this.gmtcreate = gmtcreate;
		this.uid = uid;
		this.eid = eid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(Integer productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Float getPricePurchase() {
		return this.pricePurchase;
	}

	public void setPricePurchase(Float pricePurchase) {
		this.pricePurchase = pricePurchase;
	}

	public Float getPriceSale() {
		return this.priceSale;
	}

	public void setPriceSale(Float priceSale) {
		this.priceSale = priceSale;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

}