package net.caiban.domain.auth;

import java.util.Date;

/**
 * Param generated by MyEclipse Persistence Tools
 */

public class Param implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8107987409487491206L;
	private Integer id;
	private String type;
	private String names;
	private String key;
	private String value;
	private Short sort;
	private Short used;
	private Date gmtcreate;

	// Constructors

	/** default constructor */
	public Param() {
	}

	/** minimal constructor */
	public Param(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Param(Integer id, String type, String names, String key,
			String value, Short sort, Short used, Date gmtcreate) {
		this.id = id;
		this.type = type;
		this.names = names;
		this.key = key;
		this.value = value;
		this.sort = sort;
		this.used = used;
		this.gmtcreate = gmtcreate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNames() {
		return this.names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Short getSort() {
		return this.sort;
	}

	public void setSort(Short sort) {
		this.sort = sort;
	}

	public Short getUsed() {
		return this.used;
	}

	public void setUsed(Short used) {
		this.used = used;
	}

	public Date getGmtcreate() {
		return this.gmtcreate;
	}

	public void setGmtcreate(Date gmtcreate) {
		this.gmtcreate = gmtcreate;
	}

}