package net.caiban.auth.domain;

/**
 * AuthRole generated by MyEclipse Persistence Tools
 */

public class AuthRole implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String remark;

	// Constructors

	/** default constructor */
	public AuthRole() {
	}

	/** minimal constructor */
	public AuthRole(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AuthRole(Integer id, String name, String remark) {
		this.id = id;
		this.name = name;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}