package net.caiban.auth.domain;

import java.util.Date;

/**
 * AuthUser generated by MyEclipse Persistence Tools
 */

public class AuthUser implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer deptId;
	private String username;
	private String password;
	private String email;
	private Date gmtCreated;
	private Date gmtLogin;
	private Short blocked;
	private Short steping;

	// Constructors

	/** default constructor */
	public AuthUser() {
	}

	/** minimal constructor */
	public AuthUser(Integer id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	/** full constructor */
	public AuthUser(Integer id, Integer deptId, String username,
			String password, String email, Date gmtCreated, Date gmtLogin,
			Short blocked) {
		this.id = id;
		this.deptId = deptId;
		this.username = username;
		this.password = password;
		this.email = email;
		this.gmtCreated = gmtCreated;
		this.gmtLogin = gmtLogin;
		this.blocked = blocked;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtLogin() {
		return this.gmtLogin;
	}

	public void setGmtLogin(Date gmtLogin) {
		this.gmtLogin = gmtLogin;
	}

	public Short getBlocked() {
		return this.blocked;
	}

	public void setBlocked(Short blocked) {
		this.blocked = blocked;
	}

	/**
	 * @return the steping
	 */
	public Short getSteping() {
		return steping;
	}

	/**
	 * @param steping the steping to set
	 */
	public void setSteping(Short steping) {
		this.steping = steping;
	}

	
}