package net.caiban.auth.domain;

import java.util.Date;

/**
 * AuthRight generated by MyEclipse Persistence Tools
 */

public class AuthRight implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer parentId;
	private String name;
	private String content;
	private Integer l;
	private Integer r;
	private String menu;
	private String menuUrl;
	private String menuCss;
	private Date gmtCreated;

	// Constructors

	/** default constructor */
	public AuthRight() {
	}

	/** minimal constructor */
	public AuthRight(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AuthRight(Integer id, Integer parentId, String name, String content,
			Integer l, Integer r, String menu, String menuUrl, String menuCss,
			Date gmtCreated) {
		this.id = id;
		this.parentId = parentId;
		this.name = name;
		this.content = content;
		this.l = l;
		this.r = r;
		this.menu = menu;
		this.menuUrl = menuUrl;
		this.menuCss = menuCss;
		this.gmtCreated = gmtCreated;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getL() {
		return this.l;
	}

	public void setL(Integer l) {
		this.l = l;
	}

	public Integer getR() {
		return this.r;
	}

	public void setR(Integer r) {
		this.r = r;
	}

	public String getMenu() {
		return this.menu;
	}

	public void setMenu(String menu) {
		this.menu = menu;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuCss() {
		return this.menuCss;
	}

	public void setMenuCss(String menuCss) {
		this.menuCss = menuCss;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

}